name: flutte_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kiwi: ^0.1.0
  provider: ^2.0.1
  json_serializable: ^3.0.0
  dio: ^2.1.6
  niddler_dart: ^0.2.0
  shared_preferences: ^0.5.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.1
  built_value_generator: ^6.4.0
  icapps_translations: ^0.1.2
  kiwi_generator:
    git:
      url: https://github.com/simolus3/kiwi.git
      ref: 6ead6e68b535bf935df37b29f7d25b283337225e
      path: kiwi_generator
flutter:
  uses-material-design: true
  assets:
    - assets/locale/

icapps_translations:
  api_key: 'your-api-key'
  default_language: 'nl'
  languages: ['nl','en']