name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kiwi: ^0.2.0
  dio: ^3.0.9
  retrofit: ^1.3.1+1
  provider: ^4.0.4
  json_serializable: ^3.2.5
  niddler_dart: ^0.7.4
  shared_preferences: ^0.5.6+3
  flutter_secure_storage: 3.3.1+1
  mockito: ^4.1.1
  moor: ^2.4.2
  moor_ffi: ^0.4.0
  path_provider: ^1.6.5
  flutter_svg: 0.17.1
  path: ^1.6.4
  scroll_when_needed: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^2.4.0
  build_runner: ^1.8.0
  retrofit_generator: ^1.3.1+9
  kiwi_generator: ^0.4.0
  icapps_translations: ^1.0.1
  icapps_generator: ^0.3.0
  model_generator: ^1.1.0
  icapps_license: ^0.0.6

dependency_overrides:
  analyzer: 0.39.2+1 #kiwi uses an outdated version of analyzer
  recase: 3.0.0 #moor_generator still uses 2.0.1
  dart_style: 1.3.3 #kiwi_generator still uses >=1.0.0 <1.3.0
  build: 1.2.2 #kiwi_generator still uses >>=0.12.6 <1.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/

icapps_translations:
  api_key: 'lIWZxNlOz3d461rVMeh3dw' #TODO Update this to the correct api key
  default_language: 'nl'
  languages: ['nl','en']

icapps_license:
  licenses:
    provider: https://raw.githubusercontent.com/rrousselGit/provider/master/packages/provider/LICENSE
    moor_ffi: https://raw.githubusercontent.com/simolus3/moor/develop/moor_ffi/LICENSE