name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kiwi: ^0.2.0
  provider: ^3.0.0+1
  json_serializable: ^3.1.0
  dio: ^2.1.13
  niddler_dart: ^0.4.0
  shared_preferences: ^0.5.3+4
  mockito: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.6.5
  kiwi_generator: ^0.4.0
  icapps_translations: ^0.2.0
  icapps_generator: ^0.2.0
  model_generator: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/locale/

icapps_translations:
  api_key: 'your-api-key'
  default_language: 'nl'
  languages: ['nl','en']