name: flutter_template
description: A Flutter Template to get started quickly
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  kiwi: ^0.2.0
  dio: ^3.0.9
  retrofit: ^1.3.4
  provider: ^4.1.2
  json_serializable: ^3.3.0
  niddler_dart: ^0.8.0
  shared_preferences: ^0.5.7+2
  flutter_secure_storage: 3.3.1+1
  mockito: ^4.1.1
  moor: ^3.0.2
  moor_ffi: ^0.5.0
  connectivity: ^0.4.8+6
  path_provider: ^1.6.8
  flutter_svg: ^0.17.4
  path: ^1.7.0
  scroll_when_needed: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: ^3.0.0
  build_runner: ^1.10.0
  retrofit_generator: ^1.3.4+2
  kiwi_generator: ^0.4.0
  icapps_translations: ^2.0.0
  icapps_generator: ^0.3.0
  model_generator: ^1.3.0
  icapps_license: ^0.0.6

dependency_overrides:
  build: 1.3.0 #retrofit_generator >=1.1.0+1 depends on build ^1.2.2 and kiwi_generator 0.4.0 depends on build >=0.12.6 <1.2.0, retrofit_generator >=1.1.0+1 is incompatible with kiwi_generator 0.4.0.
  dart_style: 1.3.6 #retrofit_generator >=1.1.0+1 depends on dart_style ^1.3.3 and kiwi_generator 0.4.0 depends on dart_style >=1.0.0 <1.3.0, retrofit_generator >=1.1.0+1 is incompatible with kiwi_generator 0.4.0.
  analyzer: 0.39.8 #retrofit_generator >=1.3.0 depends on analyzer ^0.39.3 and kiwi_generator 0.4.0 depends on analyzer >=0.32.4 <0.37.0, retrofit_generator >=1.3.0 is incompatible with kiwi_generator 0.4.0.
  path: 1.7.0 #Because every version of flutter_test from sdk depends on path 1.6.4 and flutter_template depends on path 1.7.0, flutter_test from sdk is forbidden.

flutter:
  uses-material-design: true
  assets:
    - assets/api/
    - assets/fonts/
    - assets/fonts/open_sans/
    - assets/locale/
    - assets/images/
    - assets/images/icons/
    - assets/images/icons/android/
    - assets/images/icons/ios/

icapps_translations:
  api_key: 'lIWZxNlOz3d461rVMeh3dw' #TODO Update this to the correct api key
  default_language: 'nl'
  languages: ['nl','en']

icapps_license:
  licenses:
    moor_ffi: https://raw.githubusercontent.com/simolus3/moor/develop/moor_ffi/LICENSE